AWSTemplateFormatVersion: "2010-09-09"
Description: Capstone Translation Pipeline – S3, Lambda, Translate

Parameters:
  LambdaZipS3Bucket:
    Type: String
    Description: S3 bucket that holds the Lambda ZIP
  LambdaZipS3Key:
    Type: String
    Description: Key (path) to the Lambda ZIP inside LambdaZipS3Bucket

Resources:

  ### 1 ▸  S3 BUCKETS
  RequestBucket:
    Type: AWS::S3::Bucket
    DependsOn: TranslateFunction                       # make sure Lambda exists first
    Properties:
      BucketName: !Sub '${AWS::StackName}-request'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 7
      NotificationConfiguration:                       # <─ THIS TRIGGERS LAMBDA
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt TranslateFunction.Arn

  ResponseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-response'

  ### 2 ▸  IAM ROLE FOR LAMBDA
  TranslateLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: {Service: lambda.amazonaws.com}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TranslateAndS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - translate:TranslateText
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ### 3 ▸  LAMBDA FUNCTION
  TranslateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-translate-fn'
      Runtime: python3.9
      Handler: translator.lambda_handler
      Role: !GetAtt TranslateLambdaExecutionRole.Arn
      Timeout: 30
      Code:
        S3Bucket: !Ref LambdaZipS3Bucket
        S3Key:    !Ref LambdaZipS3Key
      Environment:
        Variables:
          RESPONSE_BUCKET: !Ref ResponseBucket

  ### 4 ▸  PERMISSION: ALLOW S3 ➜ LAMBDA
  AllowS3InvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TranslateFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt RequestBucket.Arn

Outputs:
  RequestBucketName:  {Value: !Ref RequestBucket}
  ResponseBucketName: {Value: !Ref ResponseBucket}
  LambdaName:         {Value: !Ref TranslateFunction}
