Resources:
  RequestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-request'
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 7

  ResponseBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-response'

  TranslateLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-role'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TranslateAndS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - translate:TranslateText
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
                
Parameters:
  LambdaZipS3Bucket:
    Type: String
    Description: S3 bucket where Lambda deployment package is stored

  LambdaZipS3Key:
    Type: String
    Description: S3 key (path) to the Lambda deployment package zip file

Resources:
  TranslateFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-translate-fn'
      Handler: translator.lambda_handler
      Role: !GetAtt TranslateLambdaExecutionRole.Arn
      Runtime: python3.9
      Code:
        S3Bucket: !Ref LambdaZipS3Bucket
        S3Key: !Ref LambdaZipS3Key
      Timeout: 30

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref TranslateFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt RequestBucket.Arn

  RequestBucketNotification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref RequestBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt TranslateFunction.Arn
